version: "3.7"

services:
  shairport-sync-radio:
    network_mode: host
    build: .
    container_name: shairport-sync-radio 
    environment:
      - PORT=8080
      - DEBUG=1
      - FORMAT=WAV
    restart: unless-stopped
